### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by shivupa**

### CODE REVIEW

**Comment by amandadumi** [comment]
Did this pass locally for you? If so it's just changing the typing and I can do that. Wanted to check that you weren't already doing that before merging

**Comment by shivupa** [comment]
I screwed up a commit gotta fix it

**Comment by shivupa** [comment]
I was trying to include ccframe but I didn't finish reimplementing that

**Comment by shivupa** [comment]
ok passes but throttled on codecov again

**Pull request merged**
